Auth to correct endpoint and Bearer is working

diff --git a/Example b/Example
--- a/Example
+++ b/Example
@@ -1,10 +1,10 @@
 #!/bin/bash
 if [ ! -f authtoken ] || [ ! -f config.json ]; then
-        echo "Either authtoken or config.json is missing. Please follow the README."
-        exit 1
+	echo "Either authtoken or config.json is missing. Please follow the README."
+	exit 1
 fi
 
 TOKEN=$(cat authtoken)
+GRAPH_URL=$(jq -r .endpoints.usage config.json)
 
-GRAPH_URL=$(jq -r .endpoints.graph config.json)
-curl -s $GRAPH_URL/$1 -H "Authorization: Bearer $TOKEN" | jq .
+curl -s $GRAPH_URL --header "Authorization: "Bearer" $TOKEN " | jq
